name: CI

on: [push]

jobs:
  pipeline:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: lint commit
      run: make lint.commit
    - name: lint shellcheck
      run: make lint.shellcheck
    - name: test unit
      run: make test.unit

